version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: nestjs-app-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE:-nestjs_prod}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-NestJS App}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - postgres
    networks:
      - app-network
      - traefik

  postgres:
    image: postgres:15-alpine
    container_name: postgres-prod
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE:-nestjs_prod}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  traefik:
    external: true