http:
  routers:
    # NestJS API
    nestjs-api:
      rule: "Host(`api.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: nestjs-api
      tls:
        certResolver: letsencrypt
      middlewares:
        - secure-headers

    # Traefik Dashboard (secured)
    traefik-dashboard:
      rule: "Host(`traefik.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - basic-auth
        - secure-headers

  services:
    nestjs-api:
      loadBalancer:
        servers:
          - url: "http://nestjs-app-prod:3000"

  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "${TRAEFIK_AUTH}"

    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"