version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../traefik/config:/config:ro
    environment:
      - DOMAIN=${DOMAIN}
      - TRAEFIK_AUTH=${TRAEFIK_AUTH}
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - traefik

volumes:
  traefik_letsencrypt:

networks:
  traefik:
    external: true